name: sense_dart
version: 0.0.3
description: API Library for Dart with audio analysis and recognition solutions from Cochlear.ai
homepage: https://github.com/SejongJeong/sense_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  grpc: ^2.1.3
  protobuf: ^1.0.1

dev_dependencies: